version: "3.7"
services:
  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    image: git-server
    restart: always
    networks:
      - my-net
networks:
  my-net:
    driver: bridge